# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
# See supported Node.js release schedule at https://nodejs.org/en/about/releases/

name: Node.js CI

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: [self-hosted]
    steps:
    - name: 'Checkout repository'
      uses: actions/checkout@v3
    - name: 'Use Node.js 18'
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
    - name: 'Install dependencies'
      run: npm ci
    - name: 'Build artifacts'
      run: npm run build
    - name: 'Upload artifacts'
      uses: actions/upload-artifact@v4
      with:
        name: built_artifacts
        path: |
          public
          build
        retention-days: 0

  reload_website:
    name: 'Update website'
    runs-on: [self-hosted] 
    steps:
      - name: 'Enter folder'
        shell: bash
        run: cd ~/ws
      - name: 'Stash local edits'
        shell: bash
        run: git stash
      - name: 'Sync commits'
        shell: bash
        run: git pull
      - name: 'Install deps'
        shell: 'bash'
        run: npm i
      - name: 'Rebuild website'
        shell: bash
        run: npm run build 
      - name: 'Restart server'
        shell: bash
        run: |
          screen -S "WS" -X at "#" stuff '^C' &&
          screen -S "WS" -X at "#" stuff 'cd ~/ws \n' &&
          screen -S "WS" -X at "#" stuff 'echo "Restart" \n' &&
          screen -S "WS" -X stuff 'npm start \n'

