# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
# See supported Node.js release schedule at https://nodejs.org/en/about/releases/

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

        

    steps:
    - name: 'Checkout repository'
      uses: actions/checkout@v3
    - name: 'Use Node.js 18'
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
    - name: 'Install dependencies'
      run: npm ci
    - name: Build artifacts
      run: npm run build
    - name: 'Archive server artifacts'
      uses: actions/upload-artifact@v4
      with:
        name: server_build
        path: build
        retention-days: 0.1
    - name: Archive client artifacts
      uses: actions/upload-artifact@v4
      with:
        name: client_build
        path: public
        retention-days: 0.1
